version: '3.8'

services:
  gluelinks-test:
    image: ghcr.io/glueops/gluelinks-api:latest@sha256:349c394155876b98c0e5a3e022a506f8eb6489ac4a1f38ed3dcd10213bebe783
    ports:
      - "8001:8000"
    volumes:
      - ${HOME}/.kube/config:/home/appuser/.kube/config:ro
      - ./.env.local:/app/.env.local:ro
    environment:
      - KUBECONFIG=/home/appuser/.kube/config
    container_name: gluelinks-kubetest
